logging:
  level:
    root: ERROR

server:
  address: 127.0.0.1
  port: 0
  display-name: Integration Provisioning Tool
  context-path: /provisioning
  tomcat:
    basedir: /data/symphony/ib/tomcat

spring:
  profiles:
    active: jira, github, salesforce, universal, trello, zapier

#
# Time (in minutes) to persist in a local cache the pod certificate to check JWT signature
#
public_pod_certificate_cache_duration: 60

#
# Default timeouts (in millis)
#
http_client_config:
  connect_timeout: 10000
  read_timeout: 15000
